### PR TITLE
Use lowercase 't' for external textures MDLs

### PR DESCRIPTION
**Pull request by JoelTroch**
For operating systems and file systems where case sensitivity matters.

### CODE REVIEW

**Comment by Solokiller** [comment]
Some texture models use uppercase T so both cases need to be handled. For saving uppercase T should be used since that's what studiomdl does.

**Comment by JoelTroch** [comment]
I'll update this PR to handle both cases then.

**Comment by JoelTroch** [comment]
Changes applied, let me know if it's good or you want it implemented differently.

**Comment by Solokiller** [comment]
Looks like you're declaring a variable length array on the stack? I'm not sure if that's even allowed in C++.

I'd recommend using `std::string` and `std::filesystem::path` instead of char buffers. I'm going to rewrite file loading altogether at which point those `const char*` pointers will be replaced with `const std::filesystem::path&` along with a bunch of other changes.

**Comment by Solokiller** [comment]
I've implemented this using `std::filesystem::path`. As noted in the comment in the relevant function eventually case sensitivity will be handled by `IFileSystem`. For now this should suffice.

**Pull request closed without merging**
